name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      matrix:
        platform: [ windows-latest, ubuntu-latest ]
    
    runs-on: ${{ matrix.platform }}

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 2.2.402
    - name: Build
      run: dotnet build --configuration Release
    - name: Test
      run: dotnet test --configuration Release --results-directory artifacts --no-build  
    - name: debug
      run: | 
        pwd
        ls
        ls src
    - name: Package
      if: github.event_name != 'pull_request'
      run: dotnet pack --configuration Release --no-build
    - name: Publish nuget
      if: github.event_name != 'pull_request'
      run: dotnet nuget push src/*/bin/Release/*.nupkg
    - name: Publish Release Packages
      if: startsWith(github.ref, 'refs/tags/v')
      run: dotnet nuget push src/*/bin/Release/*.nupkg --source https://api.nuget.org/v3/index.json --api-key ${{ secrets.NUGET_TOKEN }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v1.0.0
      with:
        name: artifacts
        path: artifacts
